### ISSUE TITLE
Support for ASP.NET Core 2

### ISSUE THREAD

**Issue by AStoker** [Atalasoft/asp-net-core-demo#1]
When building a new solution aimed at .Net Core 2, the nuget packages for Atalasoft.dotImage.WebControls.Core.x86 give warnings about not being able to be used for .Net Core 2. This results in a build failure.

**Comment by guest512** [comment]
Hi Andrew,

Could you please clarify, what exact version of ASP.NET Core are you trying to use? 

Since there are two different versions of it - [ASP.NET Core (.NET Core) and ASP.NET Core (.NET Framework)](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1#aspnet-core-targeting-net-framework) - and Atalasoft controls do not support .NET Core runtime yet, you should use ASP.NET Core (.NET Framework).

Best Regards,
Denis.

**Comment by AStoker** [comment]
Hello Denis. I think part of the problem came from the tutorial (https://atalasoft.github.io/web-document-viewer/tutorial-demo-application-aspnet-core.html) where it wasn't clear what to do in setting up a Core application that targets the .Net framework. After muddling around, I noticed the differences between what comes from the tutorial and what's actually done in this sample app. Thanks for the quick response though!
